import { useMemo, useState } from "react";

import { useApprovals } from "../hooks/useApprovals";
import { useFindings } from "../hooks/useFindings";

export default function Findings() {
  const [severity, setSeverity] = useState("");
  const [status, setStatus] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const findings = useFindings({ severity: severity || undefined, status: status || undefined });
  const approvals = useApprovals();

  const selected = useMemo(
    () => (findings.data ?? []).find((item) => item.id === selectedId) ?? null,
    [findings.data, selectedId],
  );

  return (
    <>
      <div className="page-header">
        <div className="page-title">Findings</div>
        <div className="page-subtitle">Vulnerability reports generated by the judge agent</div>
      </div>

      <div className="flex-center gap-1 mb-2">
        <select className="form-select" style={{ width: "auto" }} value={severity} onChange={(e) => setSeverity(e.target.value)}>
          <option value="">All severities</option>
          <option value="CRITICAL">Critical</option>
          <option value="HIGH">High</option>
          <option value="MEDIUM">Medium</option>
          <option value="LOW">Low</option>
        </select>
        <select className="form-select" style={{ width: "auto" }} value={status} onChange={(e) => setStatus(e.target.value)}>
          <option value="">All statuses</option>
          <option value="DRAFT">Draft</option>
          <option value="FILED">Filed</option>
          <option value="PATCHED">Patched</option>
          <option value="VALIDATED">Validated</option>
        </select>
      </div>

      <div className="table-wrap mb-2">
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Category</th>
              <th>Severity</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {findings.isLoading ? (
              <tr><td colSpan={4} style={{ textAlign: "center", color: "var(--text-muted)" }}>Loading…</td></tr>
            ) : (findings.data ?? []).length === 0 ? (
              <tr><td colSpan={4} style={{ textAlign: "center", color: "var(--text-muted)" }}>No findings match the current filters</td></tr>
            ) : (
              (findings.data ?? []).map((item) => (
                <tr key={item.id} className="clickable" onClick={() => setSelectedId(item.id === selectedId ? null : item.id)}>
                  <td className="mono">{item.id.slice(0, 8)}…</td>
                  <td><strong>{item.attack_category}</strong></td>
                  <td><span className={`badge badge-${item.severity.toLowerCase()}`}>{item.severity}</span></td>
                  <td><span className={`badge badge-${item.status.toLowerCase()}`}>{item.status}</span></td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {selected ? (
        <div className="card mt-2">
          <div className="card-title">Finding detail — {selected.id}</div>
          <pre>{JSON.stringify(selected, null, 2)}</pre>
          <div className="flex gap-1 mt-2">
            {selected.severity === "CRITICAL" && selected.status === "DRAFT" ? (
              <button
                type="button"
                className="btn btn-success btn-sm"
                onClick={() => approvals.reportDecision.mutate({ reportId: selected.id, decision: "approve" })}
              >
                ✓ Approve
              </button>
            ) : null}
            <button
              type="button"
              className="btn btn-secondary btn-sm"
              onClick={() => {
                const blob = new Blob([JSON.stringify(selected, null, 2)], { type: "application/json" });
                const link = document.createElement("a");
                link.href = URL.createObjectURL(blob);
                link.download = `finding-${selected.id}.json`;
                link.click();
                URL.revokeObjectURL(link.href);
              }}
            >
              ↓ Export JSON
            </button>
            <button type="button" className="btn btn-ghost btn-sm" onClick={() => setSelectedId(null)}>
              ✕ Close
            </button>
          </div>
        </div>
      ) : null}
    </>
  );
}
